### ISSUE TITLE
Old TODO

### ISSUE THREAD

**Issue by xXSirGamesXx** [xXSirGamesXx/HungerGames#1]
- [ ] Add Kits

- [x] Add DeathMatch Toggle

- [ ] Add GUI Kit selector

- [ ] Add AdvancedKits support

- [ ] Add tap-to-add-slot support

- [ ] Add API events

- [ ] Add Command to join game automatically

- [ ] Add Statistics API

- [ ] Add spectator mode

- [ ] Add sign knockback

- [ ] Optimize plugin for better performance
